<?php
$z[0]=Array("arcurl","",196,211);
$z[1]=Array("title","",213,227);
$z[2]=Array("writer","",471,486);
$z[3]=Array("pubdate","",513,555);
$z[3][4]['function']="GetDateMk(@me)";
$z[4]=Array("arcurl","",644,659);
$z[5]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img   style='width:98px;height:43px;padding: 5px 0px 0px 0px' alt='title' src='{@me['litpic']}'/>\"); ",670,848);
$z[5][4]['runphp']="yes";

?>