<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/141007/1-14100G54010.png ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/141007/1-14100G54010.png";
$z[1][4]['text']="";
$z[1][4]['width']="600";
$z[1][4]['height']="500";
$z[2]=Array("img"," /uploads/allimg/141007/1-14100G54014.png ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/141007/1-14100G54014.png";
$z[2][4]['text']="";
$z[2][4]['width']="600";
$z[2][4]['height']="500";
$z[3]=Array("img"," /uploads/allimg/141007/1-14100G54016.png ",387,532);
$z[3][4]['ddimg']="/uploads/allimg/141007/1-14100G54016.png";
$z[3][4]['text']="";
$z[3][4]['width']="600";
$z[3][4]['height']="500";
$z[4]=Array("img"," /uploads/allimg/141007/1-14100G54020.png ",534,679);
$z[4][4]['ddimg']="/uploads/allimg/141007/1-14100G54020.png";
$z[4][4]['text']="";
$z[4][4]['width']="600";
$z[4][4]['height']="500";

?>