<?php
$z[0]=Array("list","<li>\r\n   [field:imglink/]\r\n    [field:textlink/]\r\n    <span class=\"info\">\r\n        <small>日期：</small>[field:pubdate function=\"getdatemk(@me)\"/]\r\n        <small>点击：</small>[field:click/]\r\n        <small>好评：</small>[field:scores/]\r\n    </span>\r\n    <p class=\"intro\"> [field:description/]...</p>\r\n    </li>",0,429);
$z[0][4]['pagesize']="30";
$z[0][4]['col']="1";
$z[0][4]['titlelen']="60";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";
$z[0][4]['channel']="1";

?>