<?php
$z[0]=Array("arcurl","",203,218);
$z[1]=Array("title","",220,234);
$z[2]=Array("writer","</a> &nbsp;&nbsp;[field:pubdate function=\"GetDateMk(@me)\"",403,476);
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  style='line-height: 70px;'  href='{@me['arcurl']}' class='article-img'  target='_blank'><img width='35%' height='60px' style='padding: 5px 0px 0px 0px' alt='title' src='{@me['litpic']}'/></a>\"); ",522,797);
$z[3][4]['runphp']="yes";

?>