<?php
$z[0]=Array("field","",79,95);
$z[0][4]['name']="id";
$z[1]=Array("field","",97,126);
$z[1][4]['name']="typename";
$z[2]=Array("field","",179,195);
$z[2][4]['name']="id";
$z[3]=Array("sql","  \r\n			                 <li><a href=\"[field:typeurl/]\" class=\"type[field:id/]\">[field:typename /]</a></li>\r\n			                ",221,419);
$z[3][4]['sql']="Select * from dede_arctype where reid =~id~";

?>