<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",16,170);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",186,201);
$z[2]=Array("title","",217,231);
$z[3]=Array("softrank","",299,344);
$z[3][4]['function']="GetRankStar(@me)";
$z[4]=Array("click","",382,396);
$z[5]=Array("app","",501,514);
$z[6]=Array("device_label","",522,543);
$z[7]=Array("app","",584,596);

?>