<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img  alt='' width='68' height='68'  src='{@me['litpic']}'/></a>\"); ",210,396);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",591,606);
$z[2]=Array("title","",622,636);
$z[3]=Array("softrank","",1555,1600);
$z[3][4]['function']="GetRankStar(@me)";
$z[4]=Array("app_desc","",1983,2040);
$z[4][4]['function']="cn_substr(Html2text(@me),80)";

?>