<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",5,159);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",170,187);
$z[2]=Array("arcurl","",202,217);
$z[3]=Array("title","",233,247);
$z[4]=Array("pubdate","",296,342);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",367,381);
$z[6]=Array("scores","",406,421);
$z[7]=Array("description","",454,474);
$z[8]=Array("arcurl","",759,774);
$z[9]=Array("title","",823,837);
$z[10]=Array("pubdate","",984,1030);
$z[10][4]['function']="GetDateTimeMK(@me)";
$z[11]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='article-img'  target=\"_blank\"  style=\"background-image: url({@me['litpic']})\"><img src='{@me['litpic']}'/></a>\"); ",1204,1427);
$z[11][4]['runphp']="yes";

?>