<li style="border-top: solid 1px #ddd;height: 75px;">
				  			<div style="clear:both;margin: 5px 0px 5px 0px;width:65%; float: left; font-size: 12px">
				  				<a href="[field:arcurl/]" class="all-want-txt-a">[field:title/]</a>
				  				<p style="margin: 5px 0px 5px 0px;font-size: 10px;"><strong style="color: #ddd">&nbsp;&nbsp;[field:pubdate function="MyDate('Y-m-d H:i',@me)"/]</strong></p>
				  			</div>
			  				<a href="[field:arcurl/]" style="line-height: 70px;" target="_blank"><img alt="[field:title/]" src="[field:litpic/]" style="padding: 5px 0px 0px 0px" width="35%" height="60px"></a>
						</li>