<?php
$z[0]=Array("if","---------\r\n						",0,49);
$z[0][4]['field.id']="=2";
$z[1]=Array("field","",141,169);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",181,197);
$z[2][4]['name']="id";
$z[3]=Array("field","",199,228);
$z[3][4]['name']="typename";
$z[4]=Array("field","",281,297);
$z[4][4]['name']="id";
$z[5]=Array("sql","  \r\n			                 <li><a href=\"../plus/list.php?tid=[field:id/]\" class=\"type[field:id/]\">[field:typename /]</a></li>\r\n			                ",323,537);
$z[5][4]['sql']="Select * from dede_arctype where reid =~id~";

?>