<section>
						<div class="content-card-wrapper">
							<div class="content-card">
								<!-- Article Title -->
								<div class="article-title">
									<h1></h1></a>"); [/field:array]
									<a data="2465" target="_blank" href="[field:arcurl/]" class="app-title">
										<h1>
											[field:title/] -- Nimble										</h1>
									</a>
									<div style="padding-top: 10px;" class="pub-time-and-version">
										<span class="pub-time">[field:pubdate function="GetDateTimeMK(@me)"/]</span>
									</div>
								</div>
								<a target="_blank" href="" class="detail-icon" title="进入应用详情页面"></a>
								<!-- Article Img -->
								[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href="{@me['arcurl']}" class='article-img'  target="_blank"  style="background-image: url({@me['litpic']})"><img src='{@me['litpic']}'/></a>"); [/field:array]
							</div>
							<!-- Quote Area -->
							<div class="quote-area">
								<div class="quote-words">
									<a target="_blank" href="/article/shownews/id/2465" class="quote-text">智能时代，人们对智能产品的要求也越来越高，对生活有更简便化的追求。以往有触摸的智能产品，有一键控制的智能产品，但如今有了Nimble，你只需微举手指就可以实...</a>
								</div>
								    <p>
									<a href="/index/member/personalization/tagetuser/285"><span class="user-title"></span>
									<span style="float:right" class="user-name">Mint.</span></a>
									<span class="newsimagenice">
										<i></i><span>0</span>
									</span>
								    </p>
							    </div>
						    </div>
			</section>