<?php
$z[0]=Array("arcurl","",1085,1100);
$z[1]=Array("title","",1331,1345);
$z[2]=Array("pubdate","",2037,2079);
$z[2][4]['function']="GetDateMk(@me)";
$z[3]=Array("array","@me = (empty(@me[&#39;litpic&#39;]) ? \"\" : \"&lt;a href=&#39;{@me[&#39;arcurl&#39;]}&#39; class=&#39;article-img&#39;&nbsp; target=&#39;_blank&#39;&gt;&lt;img src=&#39;{@me[&#39;litpic&#39;]}&#39;/&gt;&lt;/a&gt;\"); ",3058,3320);
$z[3][4]['runphp']="&#39;yes&#39;";
$z[4]=Array("arcurl","",4208,4223);
$z[5]=Array("description","<br />\r\n&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp; if(@me&lt;&gt;&#39;&#39; )@me = &#39; &lt;div class=\"intro\"&gt;&#39;.@me.&#39;&lt;/div&gt; &#39;;<br />\r\n&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp; ",4439,5006);
$z[5][4]['runphp']="&#39;yes&#39;";
$z[6]=Array("writer","",6067,6082);
$z[7]=Array("goodpost","",6547,6564);

?>