<div class="row">
							<div class="row app-card-in">
								<div class="col-xs-3 app-icon">
									<img width="68" height="68" src="[field:litpic /]"
										alt="" />
								</div>
								<div class="col-xs-9 app-content">
									<div class="row">
										<div class="app-title pull-left">
											<h4>[field:title /]</h4>
										</div>
										<div class="app-device-logo pull-left">
											<div class="android-logo active pull-left">
												<em class="fa fa-android"></em>
											</div>
											<div class="ios-logo active pull-left">
												<em class="fa fa-apple"></em>
											</div>
											<div class="windows-logo pull-left unsupport">
												<em class="fa fa-windows"></em>
											</div>
										</div>
										<div class="pull-right">
											<button class="btn btn-info">
												<li class="fa fa-download"></li>下载
											</button>
										</div>
									</div>
									<div class="row">
									[field:softrank/]
									[field:softrank  function='GetRankStar(@me)'/]
									
										<em class="fa fa-star"></em> <em class="fa fa-star"></em> <em
											class="fa fa-star"></em> <em class="fa fa-star"></em> <em
											class="fa fa-star-half-o"></em> 4.5
									</div>
									<div class="row">
										<p>[field:description/]</p>
									</div>
								</div>
							</div>
						</div>