<?php
$z[0]=Array("field","",51,79);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",91,107);
$z[1][4]['name']="id";
$z[2]=Array("field","",109,131);
$z[2][4]['name']="typename";
$z[3]=Array("field","",133,162);
$z[3][4]['name']="typename";
$z[4]=Array("field","",215,231);
$z[4][4]['name']="id";
$z[5]=Array("sql","  \r\n			                 <li><a href=\"../plus/list.php?tid=[field:id/]\" class=\"type[field:id/]\">[field:typename /]</a></li>\r\n			                ",257,471);
$z[5][4]['sql']="Select * from dede_arctype where reid =~id~";

?>