<?php
$z[0]=Array("arcurl","",245,260);
$z[1]=Array("title","",309,323);
$z[2]=Array("pubdate","",470,516);
$z[2][4]['function']="GetDateTimeMK(@me)";
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='article-img'  target=\"_blank\"  style=\"background-image: url({@me['litpic']})\"><img src='{@me['litpic']}'/></a>\"); ",690,913);
$z[3][4]['runphp']="yes";

?>