<?php
$z[0]=Array("arcurl","",196,211);
$z[1]=Array("title","",213,227);
$z[2]=Array("mid","",375,427);
$z[2][4]['function']="GetMemberInfos('userid',@me)";
$z[3]=Array("writer","",466,481);
$z[4]=Array("pubdate","",508,550);
$z[4][4]['function']="GetDateMk(@me)";
$z[5]=Array("arcurl","",639,654);
$z[6]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img   style='width:98px;height:43px;padding: 5px 0px 0px 0px' alt='title' src='{@me['litpic']}'/>\"); ",665,843);
$z[6][4]['runphp']="yes";

?>