<div class="col-md-12">
        <div class="dashboard-card-img">
          <a href="[field:arcurl/]"><img height="360" width="300" src="[field:litpic/]" alt=""></img></a>
        </div>
        <div class="view-card-header">
          <p>[field:title/]</p>
        </div>
        <div class="view-card-status">
          <div class="pr-sm pull-left">
            <i class="fa fa-heart-o"></i>5
          </div>
          <div class="pull-right">
            <span>共10篇智见</span>
          </div>
        </div>
      </div>