<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/141007/1-14100G54010.png ",93,241);
$z[1][4]['ddimg']="/uploads/allimg/141007/1-14100G54010-lp.png";
$z[1][4]['text']="";
$z[1][4]['width']="320";
$z[1][4]['height']="568";
$z[2]=Array("img"," /uploads/allimg/141007/1-14100G54014.png ",243,391);
$z[2][4]['ddimg']="/uploads/allimg/141007/1-14100G54014-lp.png";
$z[2][4]['text']="";
$z[2][4]['width']="320";
$z[2][4]['height']="568";
$z[3]=Array("img"," /uploads/allimg/141007/1-14100G54016.png ",393,541);
$z[3][4]['ddimg']="/uploads/allimg/141007/1-14100G54016-lp.png";
$z[3][4]['text']="";
$z[3][4]['width']="320";
$z[3][4]['height']="568";
$z[4]=Array("img"," /uploads/allimg/141007/1-14100G54020.png ",543,691);
$z[4][4]['ddimg']="/uploads/allimg/141007/1-14100G54020-lp.png";
$z[4][4]['text']="";
$z[4][4]['width']="320";
$z[4][4]['height']="568";

?>