<?php
$z[0]=Array("arcurl","",195,210);
$z[1]=Array("title","",212,226);
$z[2]=Array("arcurl","",350,365);
$z[3]=Array("writer","",406,421);
$z[4]=Array("pubdate","",448,490);
$z[4][4]['function']="GetDateMk(@me)";
$z[5]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  style='line-height: 70px;'  href='{@me['arcurl']}' class='article-img'  target='_blank'><img   style='width:98px;height:43px;padding: 5px 0px 0px 0px' alt='title' src='{@me['litpic']}'/></a>\"); ",536,810);
$z[5][4]['runphp']="yes";

?>