<?php
$z[0]=Array("arcurl","",203,218);
$z[1]=Array("title","",236,250);
$z[2]=Array("pubdate","",361,403);
$z[2][4]['function']="GetDateMk(@me)";
$z[3]=Array("array","@me = (empty(@me[&#39;litpic&#39;]) ? \"\" : \"<a class=\"article-img\" href=\"{@me[\" target=\"_blank\"><img src=\"{@me[\" /></a>\"); ",456,627);
$z[3][4]['runphp']="&#39;yes&#39;";
$z[4]=Array("arcurl","",756,771);
$z[5]=Array("description"," if(@me&lt;&gt;&#39;&#39; )@me = &#39; </a>\r\n						<div class=\"intro\">\r\n							<a class=\"quote-text\" href=\"[field:arcurl/]\" target=\"_blank\">&#39;.@me.&#39;</a></div>\r\n						<a class=\"quote-text\" href=\"[field:arcurl/]\" target=\"_blank\">&#39;; ",789,1090);
$z[5][4]['runphp']="&#39;yes&#39;";
$z[6]=Array("writer","",1217,1232);
$z[7]=Array("goodpost","",1279,1296);

?>