<section>
			<div class="content-card-wrapper">
				<div class="content-card">
					<!-- Article Title -->
					<div class="article-title">
						<h1>
							<a class="app-title" data="2465" href="[field:arcurl/]" target="_blank">[field:title/] </a></h1>
						<div class="pub-time-and-version" style="padding-top: 10px;">
							<span class="pub-time">[field:pubdate function="GetDateMk(@me)"/]</span></div>
					</div>
					<!-- Article Img -->[field:array runphp=&#39;yes&#39;]@me = (empty(@me[&#39;litpic&#39;]) ? "" : "<a class="article-img" href="{@me[" target="_blank"><img src="{@me[" /></a>"); [/field:array]</div>
				<!-- Quote Area -->
				<div class="quote-area">
					<div class="quote-words">
						<a class="quote-text" href="[field:arcurl/]" target="_blank">[field:description runphp=&#39;yes&#39;] if(@me&lt;&gt;&#39;&#39; )@me = &#39; </a>
						<div class="intro">
							<a class="quote-text" href="[field:arcurl/]" target="_blank">&#39;.@me.&#39;</a></div>
						<a class="quote-text" href="[field:arcurl/]" target="_blank">&#39;; [/field:description] </a></div>
					<p>
						<a href="/index/member/personalization/tagetuser/285"><span class="user-name" style="float:right">[field:writer/]</span></a> <span class="newsimagenice"> <span>[field:goodpost/]</span> </span></p>
				</div>
			</div>
		</section>