<?php
$z[0]=Array("arcurl","",203,218);
$z[1]=Array("title","",267,281);
$z[2]=Array("pubdate","",418,465);
$z[2][4]['function']="MyDate('Y-m-d',@me)";
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='article-img'  target='_blank'><img src='{@me['litpic']}'/></a>\"); ",640,815);
$z[3][4]['runphp']="yes";
$z[4]=Array("arcurl","",962,977);
$z[5]=Array("description","",998,1018);
$z[6]=Array("writer","",1207,1222);
$z[7]=Array("goodpost","",1298,1315);

?>