<?php
$z[0]=Array("field","",28,56);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",68,84);
$z[1][4]['name']="id";
$z[2]=Array("field","",86,115);
$z[2][4]['name']="typename";
$z[3]=Array("field","",171,187);
$z[3][4]['name']="id";
$z[4]=Array("sql","  \r\n		                 <li><a href=\"../plus/list.php?tid=[field:id/]\" class=\"type[field:id/]\">[field:typename /]</a></li>\r\n		                ",212,424);
$z[4][4]['sql']="Select * from dede_arctype where reid =~id~";

?>