<?php
$z[0]=Array("arcurl","",203,218);
$z[1]=Array("title","",254,268);
$z[2]=Array("pubdate","",397,439);
$z[2][4]['function']="GetDateMk(@me)";
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='article-img'  target='_blank'><img src='{@me['litpic']}'/></a>\"); ",614,789);
$z[3][4]['runphp']="yes";
$z[4]=Array("arcurl","",936,951);
$z[5]=Array("description","\r\n								  if(@me<>'' )@me = '\r\n								  <div class=\"intro\">'.@me.'</div>\r\n								  ';\r\n								  ",986,1139);
$z[5][4]['runphp']="yes";

?>