<?php
$z[0]=Array("arcurl","",203,218);
$z[1]=Array("title","",267,281);
$z[2]=Array("pubdate","",428,474);
$z[2][4]['function']="GetDateTimeMK(@me)";
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",649,803);
$z[3][4]['runphp']="yes";
$z[4]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href=\"{@me['arcurl']}\" class='article-img'  target=\"_blank\"  style=\"background-image: url({@me['litpic']})\"><img src='{@me['litpic']}'/></a>\"); ",813,1036);
$z[4][4]['runphp']="yes";

?>