<?php
$z[0]=Array("arcurl","",183,199);
$z[1]=Array("title","",282,297);
$z[2]=Array("pubdate","",426,473);
$z[2][4]['function']="MyDate('Y-m-d',@me)";
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img   style='display: block;' alt='title' src='{@me['litpic']}'  data-original='{@me['litpic']}'/>\"); ",653,832);
$z[3][4]['runphp']="yes";
$z[4]=Array("description","",1111,1131);
$z[5]=Array("writer","",1314,1329);

?>