<?php
$z[0]=Array("arcurl","",20,35);
$z[1]=Array("title","",66,106);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("writer","",133,148);
$z[3]=Array("typename","",175,192);
$z[4]=Array("pubdate","",220,291);
$z[4][4]['function']="strftime(\"%a, %d %b %Y %H:%M:%S +0800\",@me)";
$z[5]=Array("arcurl","",315,330);
$z[6]=Array("description","",367,413);
$z[6][4]['function']="html2text(@me)";

?>