<section>
				<div class="content-card-wrapper">
					<div class="content-card">
						<!-- Article Title -->
						<div class="article-title">
							<a class="app-title" href="[field:arcurl /]" target="_blank" data="6958a4a2cc2eabcf9071d055e658deea">
								<h1>
									[field:title /]								</h1>
							</a>
							<div class="pub-time-and-version" style="padding-top: 10px;">
								<span class="pub-time">2014-06-29</span>
							</div>
						</div>
						<!-- Article Img -->
						<a class="article-img" href="/article/shownews/id/6958a4a2cc2eabcf9071d055e658deea" target="_blank"><img alt="路痴的福音来了！ -- No Place Like Home #智能穿戴" src="/Uploads/UserFiles/Image/2014-07-27/53d4648e9162a.jpg" data-original="/Uploads/UserFiles/Image/2014-07-27/53d4648e9162a.jpg" style="display: block;"></a>
					</div>
					<!-- Quote Area -->
					<div class="quote-area">
						<div class="quote-words">
							<div class="quote-icon"></div>
							<a class="quote-text" href="/article/shownews/id/6958a4a2cc2eabcf9071d055e658deea" target="_blank">大家还记得童话故事《绿野仙踪》里那位善良的小菇凉多萝茜（Dorothy）吗？她只要碰三下鞋子就可以回家了。现在你也可以啦！...</a>
						</div>
						<p>
							<a href="/index/member/personalization/tagetuser/312"><span class="user-title"></span>
							<span class="user-name" style="float:right">从此清纯是路人</span></a>
							<span class="newsimagenice">
								<i></i><span>81</span>
							</span>
						</p>
					</div>
				 </div>
			</section>