<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/141007/1-14100G54010.png ",93,198);
$z[1][4]['ddimg']="";
$z[1][4]['text']="";
$z[1][4]['width']="320";
$z[1][4]['height']="568";
$z[2]=Array("img"," /uploads/allimg/141007/1-14100G54014.png ",200,305);
$z[2][4]['ddimg']="";
$z[2][4]['text']="";
$z[2][4]['width']="320";
$z[2][4]['height']="568";
$z[3]=Array("img"," /uploads/allimg/141007/1-14100G54016.png ",307,412);
$z[3][4]['ddimg']="";
$z[3][4]['text']="";
$z[3][4]['width']="320";
$z[3][4]['height']="568";
$z[4]=Array("img"," /uploads/allimg/141007/1-14100G54020.png ",414,519);
$z[4][4]['ddimg']="";
$z[4][4]['text']="";
$z[4][4]['width']="320";
$z[4][4]['height']="568";

?>