<li class="community-app-wrapper">
								<div class="community-app-info-wrapper">
									<img alt="" class="community-app-cover" src="[field:litpic/]" width="100%;" height="181">
									<div class="caption" style="bottom: -191px;">
										<a href="[field:arcurl/]" target="_blank">
											<span>&nbsp;&nbsp;&nbsp;&nbsp;[field:description/]</span>
										</a>
									</div>
								</div>
								<div class="totpic_title">
									<span class="lSpan">
										<a href="[field:arcurl/]" target="_blank">
											[field:title/]										</a>
									</span>
									<span class="rSpan">文章(<a href="[field:arcurl/]" target="_blank">[field:templet/]</a>)</span>
								</div>
							</li>