<?php
$z[0]=Array("field","",51,72);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",84,100);
$z[1][4]['name']="id";
$z[2]=Array("field","",102,131);
$z[2][4]['name']="typename";
$z[3]=Array("field","",184,200);
$z[3][4]['name']="id";
$z[4]=Array("sql","  \r\n			                 <li><a href=\"[field:typeurl/]\" class=\"type[field:id/]\">[field:typename /]</a></li>\r\n			                ",226,424);
$z[4][4]['sql']="Select * from dede_arctype where reid =~id~";

?>