<li style="border-top: solid 1px #ddd; height: 75px;">
						<div
							style="clear: both; margin: 5px 0px 5px 0px; width: 65%; float: left; font-size: 12px">
							<a class="all-want-txt-a" href="[field:arcurl/]">[field:title/]</a>
							<p style="margin: 5px 0px 5px 0px; font-size: 10px;">
								<strong style="color: #ddd"><a
									href="[field]"
									class="all-want-txt-a-10"> [field:writer]</a> &nbsp;&nbsp;[field:pubdate function="GetDateMk(@me)"/]</strong>
							</p>
						</div> <a target="_blank" style="line-height: 70px;"
						href="[field:arcurl/]"> <img width="35%" height="60px"
							style="padding: 5px 0px 0px 0px"
							src="/Uploads/UserFiles/Image/2014-07-26/53d384dc92358.jpg"
							alt="再刷你就裸了 -- X.pose"></a>
							 [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a  style='line-height: 70px;'  href='{@me['arcurl']}' class='article-img'  target='_blank'><img width='35%' height='60px' style='padding: 5px 0px 0px 0px' alt='title' src='{@me['litpic']}'/></a>"); [/field:array]
							
					</li>