  
				            <li>  
				                <a href='[field:typeurl/]' [field:rel/]>  
				                    <span class="cn">[field:typename/]</span>  
				                    <span class="en">[field:typedir runphp='yes' commet="获得最后目录名，英文"]  
				                        $l=split("/", @me);  
				                        @me=array_pop($l);  
				                    [/field:typedir]</span>  
				                </a>  
				            </li>  
				            