<?php
$z[0]=Array("note","",0,68);
$z[0][4]['type']="specialtopic";
$z[0][4]['isnull']="true";
$z[0][4]['default']="";
$z[0][4]['rename']="";
$z[1]=Array("total","\r\n",69,225);
$z[1][4]['itemname']="专题文档数";
$z[1][4]['autofield']="1";
$z[1][4]['notsend']="0";
$z[1][4]['type']="int";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="0";
$z[1][4]['default']="42";
$z[1][4]['maxlength']="250";
$z[1][4]['page']="";

?>