<?php
$z[0]=Array("arcurl","",203,218);
$z[1]=Array("title","",267,281);
$z[2]=Array("pubdate","",418,464);
$z[2][4]['function']="GetDateTimeMK(@me)";
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='article-img'  target='_blank'><img src='{@me['litpic']}'/></a>\"); ",639,814);
$z[3][4]['runphp']="yes";
$z[4]=Array("arcurl","",961,976);
$z[5]=Array("description","",997,1017);
$z[6]=Array("writer","",1206,1221);
$z[7]=Array("goodpost","",1297,1314);

?>