<?php
$z[0]=Array("arcurl","",203,218);
$z[1]=Array("title","",254,268);
$z[2]=Array("pubdate","",397,439);
$z[2][4]['function']="GetDateMk(@me)";
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='article-img'  target='_blank'><img src='{@me['litpic']}'/></a>\"); ",614,789);
$z[3][4]['runphp']="yes";
$z[4]=Array("arcurl","",936,951);
$z[5]=Array("description","\r\n										  if(@me<>'' )@me = ' <div class=\"intro\">'.@me.'</div> ';\r\n										  ",986,1121);
$z[5][4]['runphp']="yes";
$z[6]=Array("writer","",1321,1336);
$z[7]=Array("goodpost","",1411,1428);

?>