<div class="row app-card-in">
            <div class="col-xs-3 app-icon">
              <a href="[field:arcurl/]"><img width="68" height="68" src="[field:litpic/]" alt=""></img></a>
              
            </div>
            <div class="col-xs-9 app-content">
              <div class="row">
                <div class="app-title pull-left">
                </div>
                <a  href="[field:arcurl/]" >
                  <h4>[field:title/]</h4>
				</a>
                <div class="app-device-logo pull-left">
                  <div class="android-logo active pull-left">
                    <em class="fa fa-android"></em>
                  </div>
                  <div class="ios-logo active pull-left">
                    <em class="fa fa-apple"></em>
					
                  </div>
                </div>
                <div class="pull-right">
                	 [field:softlinks /]
                  <a class="btn btn-info" href=" [field:softlinks /]">
                  <li class="fa fa-download"></li>下载
                  </a>
                </div>
              </div>
              <div class="row">
                [field:softrank  function='GetRankStar(@me)'/]
				[field:softrank/]
              </div>
            </div>
          </div>