<?php
$z[0]=Array("litpic","",140,156);
$z[1]=Array("title","",328,343);
$z[2]=Array("softrank","",1019,1065);
$z[2][4]['function']="GetRankStar(@me)";
$z[3]=Array("softrank","",1076,1093);
$z[4]=Array("description","",1153,1173);
$z[5]=Array("litpic","",1387,1403);
$z[6]=Array("title","",1575,1590);
$z[7]=Array("softrank","",2266,2312);
$z[7][4]['function']="GetRankStar(@me)";
$z[8]=Array("softrank","",2323,2340);

?>