<?php
$z[0]=Array("arcurl","",183,199);
$z[1]=Array("title","",282,297);
$z[2]=Array("pubdate","",426,473);
$z[2][4]['function']="MyDate('Y-m-d',@me)";
$z[3]=Array("arcurl","",574,590);
$z[4]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img   style='display: block;' alt='title' src='{@me['litpic']}'  data-original='{@me['litpic']}'/>\"); ",616,795);
$z[4][4]['runphp']="yes";
$z[5]=Array("arcurl","",994,1010);
$z[6]=Array("description","",1037,1057);
$z[7]=Array("mid","",1131,1183);
$z[7][4]['function']="GetMemberInfos('userid',@me)";
$z[8]=Array("writer","",1287,1302);
$z[9]=Array("goodpost","",1373,1390);

?>