<?php
$z[0]=Array("arcurl","",195,210);
$z[1]=Array("title","",212,226);
$z[2]=Array("arcurl","",350,365);
$z[3]=Array("writer","</a> \r\n								&nbsp;&nbsp;[field:pubdate function=\"GetDateMk(@me)\"",406,489);
$z[4]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  style='line-height: 70px;'  href='{@me['arcurl']}' class='article-img'  target='_blank'><img   style='width:98px;height:43px;padding: 5px 0px 0px 0px' alt='title' src='{@me['litpic']}'/></a>\"); ",535,809);
$z[4][4]['runphp']="yes";

?>