<?php
$z[0]=Array("field","",169,190);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",206,235);
$z[1][4]['name']="typename";
$z[2]=Array("sql","  \r\n              <li role=\"presentation\"><a href=\"[field:typeurl/]\" tabindex=\"-1\" role=\"menuitem\" class=\"type[field:id/]\">[field:typename /]</a></li>\r\n               ",385,623);
$z[2][4]['sql']="Select * from dede_arctype where reid =~id~";

?>