<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img  alt='' width='68' height='68'  src='{@me['litpic']}'/></a>\"); ",91,277);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",472,487);
$z[2]=Array("title","",503,517);
$z[3]=Array("softrank","",1436,1481);
$z[3][4]['function']="GetRankStar(@me)";
$z[4]=Array("app_desc","",1864,1921);
$z[4][4]['function']="cn_substr(Html2text(@me),80)";

?>