<?php
$z[0]=Array("arcurl","",21,36);
$z[1]=Array("title","",67,107);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("writer","",134,149);
$z[3]=Array("typename","",176,193);
$z[4]=Array("pubdate","",221,292);
$z[4][4]['function']="strftime(\"%a, %d %b %Y %H:%M:%S +0800\",@me)";
$z[5]=Array("arcurl","",317,332);
$z[6]=Array("description","",369,415);
$z[6][4]['function']="html2text(@me)";

?>