<item> 
   
<link>/[field:arcurl/]</link> 
   
<title><![CDATA[[field:title function='html2text(@me)'/]]]></title> 
   
<author>[field:writer/]</author> 
   
<category>[field:typename/]</category> 
   
<pubDate>[field:pubdate function='strftime("%a, %d %b %Y %H:%M:%S +0800",@me)'/]</pubDate> 
   
<guid>/[field:arcurl/]</guid> 
   
<description><![CDATA[[field:description function='html2text(@me)'/]]]></description> 
   
</item>