<?php
$z[0]=Array("global","",30,59);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",132,158);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",180,207);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",235,265);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",332,358);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",389,418);
$z[5][4]['name']="cfg_adminemail";
$z[6]=Array("arclist"," \r\n   \r\n<item> \r\n<title><![CDATA[[field:title function='html2text(@me)'/]]]></title> \r\n<link>http://ad.geekview.cn[field:arcurl/]</link> \r\n<author>[field:writer/]</author> \r\n<category>[field:typename/]</category> \r\n<pubDate>[field:pubdate function='strftime(\"%a, %d %b %Y %H:%M:%S +0800\",@me)'/]</pubDate> \r\n<description><![CDATA[[field:description function='html2text(@me)'/]]]></description> \r\n</item> \r\n   \r\n",438,929);
$z[6][4]['row']="100";
$z[6][4]['col']="1";
$z[6][4]['titlelen']="200";
$z[6][4]['orderby']="pubdate";

?>