<?php
$z[0]=Array("global","",30,59);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",104,133);
$z[1][4]['name']="typename";
$z[2]=Array("field","",149,178);
$z[2][4]['name']="typelink";
$z[3]=Array("field","",200,252);
$z[3][4]['name']="title";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("field","",316,344);
$z[4][4]['name']="powerby";
$z[5]=Array("field","",372,403);
$z[5][4]['name']="adminemail";
$z[6]=Array("rssitem","\r\n<item>\r\n    <title><![CDATA[[field:title/]]]></title>\r\n    <link>[field:fullurl/]</link>\r\n    <description><![CDATA[[field:description function='html2text(@me)'/]]]></description>\r\n    <pubDate>[field:stime/]</pubDate>\r\n    <category>[field:typename/]</category>\r\n    <author>[field:writer/]</author>\r\n    <comments>[field:source/]</comments>\r\n</item>\r\n",417,801);

?>